### ISSUE TITLE
Add `matricks auto` config override options

### ISSUE THREAD

**Issue by wymcg** [wymcg/matricks#56]
Add all `matricks manual` options to `matricks auto`, so that individual settings in a configuration file can be overridden by the user. For example given a config file `example.toml`:
```toml
[matrix]
width = 12
height = 12
fps = 30.0
serpentine = true
brightness = 255

[plugin]
path = "example_plugin.wasm"
loop_plugins = false
```

Running `matricks auto example.toml  --fps 60` should run the plugin at 60 FPS, instead of 30 FPS as specified in `example.toml`.
